name: Deploy Dockerimage to Rapberry Pi

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  CONTAINER_NAME: "hello-world-container"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build Dockerimage
        run: |
          cd flask-docker
          sudo docker build --tag python-docker .

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Stop Running Container
        run: |
          CONTAINER_ID=$(sudo docker ps -q --filter "name=$CONTAINER_NAME")

          if [ -n "$CONTAINER_ID" ]; then
            echo "Stopping container $CONTAINER_NAME..."
            sudo docker stop $CONTAINER_ID
            sudo docker rm -f $CONTAINER_NAME
          else
            echo "No running container with name $CONTAINER_NAME found."
          fi

      - name: Run Container
        run: sudo docker run -d -p 8080:5000 --name $CONTAINER_NAME python-docker:latest

  cleanup:
    runs-on: self-hosted
    needs: deploy
    steps:
      - name: Remove unused images
        run: sudo docker images -qa -f 'dangling=true'
