name: Deploy to Rapberry Pi

on:
  push:
    branches: [main]

  workflow_dispatch:

env:
  FLASK_APP: api/app.py

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Create new virtual env and activate it
        run: |
          python3 -m venv flask-env
          source flask-env/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install gunicorn

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Kill gunicorn
        run: pkill gunicorn || true

      - name: Run gunicorn
        run: |
          source flask-env/bin/activate
          RUNNER_TRACKING_ID=""
          gunicorn -w 1 -b 0.0.0.0:4000 app:app -D --log-file=gunicorn.log
